{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Document Extraction API",
    "description" : "This API extracts information from documents and provides extracted data along with coordinates and confidence levels.\n",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "paths" : {
    "/extract" : {
      "post" : {
        "summary" : "Extract information from a document",
        "description" : "Upload a document to extract information from it.\n",
        "requestBody" : {
          "content" : {
            "multipart/form-data" : {
              "schema" : {
                "$ref" : "#/components/schemas/extract_body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Successful extraction",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Rect" : {
        "type" : "object",
        "properties" : {
          "x" : {
            "type" : "number"
          },
          "y" : {
            "type" : "number"
          },
          "width" : {
            "type" : "number"
          },
          "height" : {
            "type" : "number"
          }
        },
        "example" : {
          "x" : 6.027456183070403,
          "width" : 5.962133916683182,
          "y" : 1.4658129805029452,
          "height" : 5.637376656633329
        }
      },
      "RawChar" : {
        "type" : "object",
        "properties" : {
          "char" : {
            "type" : "string"
          },
          "rect" : {
            "$ref" : "#/components/schemas/Rect"
          },
          "confidence" : {
            "type" : "number"
          }
        },
        "example" : {
          "rect" : null,
          "confidence" : 2.3021358869347655,
          "char" : "char"
        }
      },
      "Field" : {
        "required" : [ "name", "rawText", "rect" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string"
          },
          "value" : {
            "type" : "string"
          },
          "valueType" : {
            "type" : "string",
            "enum" : [ "text", "number", "currency" ]
          },
          "confidence" : {
            "type" : "number"
          },
          "rect" : {
            "$ref" : "#/components/schemas/Rect"
          },
          "rawText" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/RawChar"
            }
          }
        },
        "example" : {
          "rect" : {
            "x" : 6.027456183070403,
            "width" : 5.962133916683182,
            "y" : 1.4658129805029452,
            "height" : 5.637376656633329
          },
          "rawText" : [ {
            "rect" : null,
            "confidence" : 2.3021358869347655,
            "char" : "char"
          }, {
            "rect" : null,
            "confidence" : 2.3021358869347655,
            "char" : "char"
          } ],
          "valueType" : "text",
          "confidence" : 0.8008281904610115,
          "name" : "name",
          "value" : "value"
        }
      },
      "FieldGroup" : {
        "type" : "object",
        "properties" : {
          "groupName" : {
            "type" : "string"
          },
          "fields" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Field"
            }
          }
        },
        "example" : {
          "groupName" : "groupName",
          "fields" : [ {
            "rect" : {
              "x" : 6.027456183070403,
              "width" : 5.962133916683182,
              "y" : 1.4658129805029452,
              "height" : 5.637376656633329
            },
            "rawText" : [ {
              "rect" : null,
              "confidence" : 2.3021358869347655,
              "char" : "char"
            }, {
              "rect" : null,
              "confidence" : 2.3021358869347655,
              "char" : "char"
            } ],
            "valueType" : "text",
            "confidence" : 0.8008281904610115,
            "name" : "name",
            "value" : "value"
          }, {
            "rect" : {
              "x" : 6.027456183070403,
              "width" : 5.962133916683182,
              "y" : 1.4658129805029452,
              "height" : 5.637376656633329
            },
            "rawText" : [ {
              "rect" : null,
              "confidence" : 2.3021358869347655,
              "char" : "char"
            }, {
              "rect" : null,
              "confidence" : 2.3021358869347655,
              "char" : "char"
            } ],
            "valueType" : "text",
            "confidence" : 0.8008281904610115,
            "name" : "name",
            "value" : "value"
          } ]
        }
      },
      "extract_body" : {
        "type" : "object",
        "properties" : {
          "document" : {
            "type" : "string",
            "format" : "binary"
          }
        }
      },
      "inline_response_200" : {
        "type" : "object",
        "properties" : {
          "fieldGroups" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/FieldGroup"
            }
          }
        },
        "example" : {
          "fieldGroups" : [ {
            "groupName" : "groupName",
            "fields" : [ {
              "rect" : {
                "x" : 6.027456183070403,
                "width" : 5.962133916683182,
                "y" : 1.4658129805029452,
                "height" : 5.637376656633329
              },
              "rawText" : [ {
                "rect" : null,
                "confidence" : 2.3021358869347655,
                "char" : "char"
              }, {
                "rect" : null,
                "confidence" : 2.3021358869347655,
                "char" : "char"
              } ],
              "valueType" : "text",
              "confidence" : 0.8008281904610115,
              "name" : "name",
              "value" : "value"
            }, {
              "rect" : {
                "x" : 6.027456183070403,
                "width" : 5.962133916683182,
                "y" : 1.4658129805029452,
                "height" : 5.637376656633329
              },
              "rawText" : [ {
                "rect" : null,
                "confidence" : 2.3021358869347655,
                "char" : "char"
              }, {
                "rect" : null,
                "confidence" : 2.3021358869347655,
                "char" : "char"
              } ],
              "valueType" : "text",
              "confidence" : 0.8008281904610115,
              "name" : "name",
              "value" : "value"
            } ]
          }, {
            "groupName" : "groupName",
            "fields" : [ {
              "rect" : {
                "x" : 6.027456183070403,
                "width" : 5.962133916683182,
                "y" : 1.4658129805029452,
                "height" : 5.637376656633329
              },
              "rawText" : [ {
                "rect" : null,
                "confidence" : 2.3021358869347655,
                "char" : "char"
              }, {
                "rect" : null,
                "confidence" : 2.3021358869347655,
                "char" : "char"
              } ],
              "valueType" : "text",
              "confidence" : 0.8008281904610115,
              "name" : "name",
              "value" : "value"
            }, {
              "rect" : {
                "x" : 6.027456183070403,
                "width" : 5.962133916683182,
                "y" : 1.4658129805029452,
                "height" : 5.637376656633329
              },
              "rawText" : [ {
                "rect" : null,
                "confidence" : 2.3021358869347655,
                "char" : "char"
              }, {
                "rect" : null,
                "confidence" : 2.3021358869347655,
                "char" : "char"
              } ],
              "valueType" : "text",
              "confidence" : 0.8008281904610115,
              "name" : "name",
              "value" : "value"
            } ]
          } ]
        }
      }
    }
  }
}
